name: SkyWars
api: 5.0.0
main: com\Skywars\Loader
version: 1.0.0
author: WzyGee-Dev
commands:
  swcreate:
    permission: skywars.command.swcreate
  swsign:
    permission: skywars.command.swsign
  swentity:
    permission: skywars.command.swentity

permissions:
  skywars.command.swcreate:
    default: true
  skywars.command.swsign:
    default: true
  skywars.command.swentity:
    default: true